AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl

Outputs:
  DeployBucket:
    Value: !Ref DeployBucket
