AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BuildIdentifier:
    Type: String

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl

  LambdaBff:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Handler: bff.handler
      Code:
        S3Bucket: !Ref DeployBucket
        S3Key: !Sub ${BuildIdentifier}.zip

  BffRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Can run BFF lambda
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: BffExecute
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt LambdaBff.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Bare minimum lambda execution role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  BffApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${AWS::StackName}-bff-api
      ProtocolType: HTTP
      CredentialsArn: !GetAtt BffRole.Arn
      Target: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations
        - FunctionArn: !GetAtt LambdaBff.Arn

Outputs:
  DeployBucket:
    Value: !Ref DeployBucket
