AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BuildIdentifier:
    Type: String

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl

  BffFailureParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /app/${AWS::StackName}/failure-lambda-config/bff
      Description: failure-lambda config for bff lambda
      Type: String
      Value: '{"isEnabled":false,"failureMode":"latency","rate":1,"minLatency":100,"maxLatency":400,"exceptionMsg":"error","statusCode":404,"diskSpace":100,"denylist":[]}'

  LambdaBff:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Handler: bff.handler
      Code:
        S3Bucket: !Ref DeployBucket
        S3Key: !Sub ${BuildIdentifier}.zip
      Environment:
        Variables:
          FAILURE_INJECTION_PARAM: !Ref BffFailureParam

  FailureParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app/failure-lambda-config/bff
      Description: failure-lambda config
      Type: String
      Value: '{"isEnabled":false,"failureMode":"latency","rate":1,"minLatency":100,"maxLatency":400,"exceptionMsg":"error","statusCode":404,"diskSpace":100,"denylist":[]}'

  BffRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Can run BFF lambda
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: BffExecute
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt LambdaBff.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Bare minimum lambda execution role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: Failure-lambda-param
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - SSM:GetParametersByPath
                  - SSM:GetParameters
                  - SSM:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/${AWS::StackName}/failure-lambda-config/*

  BffApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${AWS::StackName}-bff-api
      ProtocolType: HTTP
      CredentialsArn: !GetAtt BffRole.Arn
      Target: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations
        - FunctionArn: !GetAtt LambdaBff.Arn

Outputs:
  DeployBucket:
    Value: !Ref DeployBucket
  WebUri:
    Value: !Sub https://${BffApi}.execute-api.${AWS::Region}.amazonaws.com/
